name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.*'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run tests
        run: |
          pytest --html=pytest_report.html

      - name: Run Flake8 linting
        run: |
          flake8 --format=html --htmldir=flake8_reports
          
      - name: Upload pytest report
        uses: actions/upload-artifact@v2
        with:
          name: pytest-report
          path: pytest_report.html

      - name: Upload flake8 report
        uses: actions/upload-artifact@v2
        with:
          name: flake8-report
          path: flake8_reports


